"""
services/report_generator.py
─────────────────────────────
Generates a clinical PDF report for brain tumor analysis.
"""

import base64
from io import BytesIO
from datetime import datetime
from fpdf import FPDF
from typing import Optional


class ClinicalReport(FPDF):
    def header(self):
        # Logo placeholder or Title
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(79, 70, 229)  # Neural-600 color
        self.cell(0, 10, "NeuroScan AI - Clinical Report", ln=True, align="C")
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | AI-Assisted Diagnosis Report (Research/Educational Use Only)", align="C")


def generate_pdf_report(
    user_name: str,
    prediction_data: dict,
) -> bytes:
    pdf = ClinicalReport()
    pdf.add_page()
    
    # ── Patient/User Info ─────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "1. Patient Information", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(50, 8, "Attending Professional:", border=0)
    pdf.cell(0, 8, user_name, ln=True)
    pdf.ln(5)

    # ── AI Findings ───────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "2. AI Diagnostic Findings", ln=True)
    
    pdf.set_font("Helvetica", "B", 11)
    status = "TUMOR DETECTED" if prediction_data['tumor_detected'] else "NO TUMOR DETECTED"
    pdf.set_text_color(220, 38, 38) if prediction_data['tumor_detected'] else pdf.set_text_color(22, 163, 74)
    pdf.cell(50, 8, "Primary Status:", border=0)
    pdf.cell(0, 8, status, ln=True)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)
    if prediction_data['tumor_detected']:
        pdf.cell(50, 8, "Tumor Type:", border=0)
        pdf.cell(0, 8, str(prediction_data.get('tumor_type', 'Unknown')).capitalize(), ln=True)
    
    pdf.cell(50, 8, "Confidence Score:", border=0)
    pdf.cell(0, 8, f"{prediction_data['confidence']*100:.2f}%", ln=True)
    
    pdf.cell(50, 8, "Uncertainty (MC Delta):", border=0)
    pdf.cell(0, 8, f"{prediction_data['uncertainty']:.4f}", ln=True)
    
    pdf.cell(50, 8, "Reliability Status:", border=0)
    pdf.cell(0, 8, prediction_data['reliability'], ln=True)
    pdf.ln(5)

    # ── Heatmap Visualization ───────────────────────────────────────────────
    if 'heatmap_image' in prediction_data and prediction_data['heatmap_image']:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "3. Explainability Visualization (Grad-CAM++)", ln=True)
        
        # Decode base64 to bytes for FPDF
        header, encoded = prediction_data['heatmap_image'].split(",", 1)
        img_data = base64.b64decode(encoded)
        img_file = BytesIO(img_data)
        
        # Add image
        pdf.image(img_file, x=40, w=120)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 10, "Heatmap highlights regions most influential to the model's prediction.", ln=True, align="C")
        pdf.ln(5)

    # ── Clinical Risk Assessment ──────────────────────────────────────────────
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "4. Clinical Risk Assessment", ln=True)
    
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(50, 8, "Risk Level:", border=0)
    pdf.cell(0, 8, prediction_data['risk_level'], ln=True)
    
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Clinical Notes:", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, prediction_data['clinical_note'].encode('latin-1', 'replace').decode('latin-1'))
    pdf.ln(2)
    
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Recommendations:", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, prediction_data['recommendation'].encode('latin-1', 'replace').decode('latin-1'))
    
    # ── Disclaimer ────────────────────────────────────────────────────────────
    pdf.ln(10)
    pdf.set_fill_color(248, 250, 252)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    disclaimer = (
        "Medical Disclaimer: This report is automatically generated by an artificial intelligence system. "
        "It is intended for clinical decision support and research purposes ONLY. "
        "The findings must be interpreted and validated by a board-certified radiologist or neurosurgeon "
        "before any patient-facing decisions or treatments are initiated."
    )
    pdf.multi_cell(0, 5, disclaimer, border=1, align="L", fill=True)

    return pdf.output()
